name: rapatory
description: Attendance with technology QR Code for Android and iOS
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # Flutter plugin for displaying inline video with other Flutter widgets on Android and iOS.
  video_player: ^0.10.2+1

  # Font Awesome Icon pack available as Flutter Icons.
  font_awesome_flutter: ^8.5.0

  # Flutter plugin for using the native TwitterKit SDKs on Android and iOS.
  flutter_twitter_login: ^1.1.0

  # Flutter plugin for Firebase Auth, enabling Android and iOS authentication using passwords,
  # phone numbers and identity providers like Google, Facebook and Twitter.
  firebase_auth: ^0.14.0+5

  # Flutter plugin for using the native Facebook Login SDKs on Android and iOS.
  flutter_facebook_login: ^3.0.0

  # Flutter package that helps implement the BLoC pattern.
  flutter_bloc: ^0.21.0

  # Flutter plugin for reading and writing simple key-value pairs.
  shared_preferences: ^0.5.3+4

  # Powerful HTTP client for Dart, which supports interceptors, FormData, Request Cancellation,
  # File Downloading, Timeout etc.
  dio: ">=3.0.3 <6.0.0"

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^3.2.3

  # Flutter plugin for Google Sign-in, a secure authentication system for signing with a Google account
  # on Android and iOS.
  google_sign_in: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Tools to write binaries that run builders.
  build_runner: ^1.7.1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - secrets.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
